import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ISSUE TRACKER",
  description: "Generated by Subhanshu jha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme> <Navbar/>
        {children}
        </Theme>
       </body>
    </html>
  );
}
